### ISSUE TITLE
[Discussion] Does dadb commands work on real device (not emulator)?

### ISSUE THREAD

**Issue by kiranpuppala** [mobile-dev-inc/dadb#10]

**Comment by Leland-Takamine** [comment]
This isn't supported yet but we plan to look into it in the future. We have an issue already open for this so closing this as a duplicate of #3

**Comment by Leland-Takamine** [comment]
@kiranpuppala I've added documentation for connecting to a real device:

https://github.com/mobile-dev-inc/dadb#connecting-to-a-physical-device

Please let me know if this doesn't work for you use case! 🙏
