### ISSUE TITLE
Issue while discovering local device 

### ISSUE THREAD

**Issue by sunnyg522** [mobile-dev-inc/dadb#12]
I am using dadb and it was not able to discover local device, 

I am using following code to discover locally connected device
val dadb = Dadb.discover("localhost")
if (dadb == null) throw RuntimeException("No adb device found")

I ran into following error 
java.lang.RuntimeException: No adb device found

**Comment by dmitry-zaitsev** [comment]
@sunnyg522 was the device connected via USB or was it an emulator?

**Comment by Leland-Takamine** [comment]
Closing due to lack of context. @sunnyg522 Feel free to reopen if you can provide more context
