### ISSUE TITLE
Does it work with Android application?

### ISSUE THREAD

**Issue by sharpordie** [mobile-dev-inc/dadb#17]
I am using computer with adb installed to update some apps on my nvidia shield.
My nvidia shield has network debugging enabled.

I would like to create an android app that could "send adb commands" to my shield.
Can I use your library for this purpose or is it only intended to be used on desktop?
Is there any special permission to give to the android application?

**Comment by dmitry-zaitsev** [comment]
@sharpordie hypothetically, this should work on Android as well. When creating a `dadb` instance you would need to provide an IP address of your Nvidia Shield device and make sure they can see each other (i.e. you are on the same WiFi network).

**Comment by dmitry-zaitsev** [comment]
Could you share a code snippet?

**Comment by sharpordie** [comment]
I created an Empty Compose Activity in Android Studio and modified three files.

#### ComposeApp/app/build.gradle

```
... // Remove for brevity

packagingOptions {

    resources.excludes.add("META-INF/*")

}

dependencies {

    ... // Remove for brevity

    implementation 'dev.mobile:dadb:0.0.9'

}
```

#### ComposeApp/app/src/main/AndroidManifest.xml

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools"
        package="com.example.composeapp">
    <uses-permission android:name="android.permission.INTERNET"/>
    <application
            android:allowBackup="true"
            android:dataExtractionRules="@xml/data_extraction_rules"
            android:fullBackupContent="@xml/backup_rules"
            android:icon="@mipmap/ic_launcher"
            android:label="@string/app_name"
            android:roundIcon="@mipmap/ic_launcher_round"
            android:supportsRtl="true"
            android:theme="@style/Theme.ComposeApp"
            tools:targetApi="31">
        <activity
                android:name=".MainActivity"
                android:exported="true"
                android:label="@string/app_name"
                android:theme="@style/Theme.ComposeApp">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
```

#### ComposeApp/app/src/main/java/com/example/composeapp/MainActivity.kt

```kotlin
package com.example.composeapp

import android.os.Bundle
import android.widget.Toast
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxHeight
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.material.Button
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import dadb.Dadb

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            Main()
        }
    }
}

@Composable
fun Main() {
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .fillMaxHeight(),
        verticalArrangement = Arrangement.Center,
        horizontalAlignment = Alignment.CenterHorizontally,
    )
    {
        val context = LocalContext.current
        Button(onClick = {
            val dadb = Dadb.discover("192.168.1.62")
            val message = if (dadb == null) "Shield was not found :(" else "Shield was found :)"
            Toast.makeText(context, message, Toast.LENGTH_LONG).show()
        }) {
            Text(text = "DISCOVER")
        }
    }
}
```

The discover method always returns null.

**Comment by dmitry-zaitsev** [comment]
Ah, right. `discover` method takes a second optional parameter `AdbKeyPair` in order to authorize the connection. By default, we are trying to look up `.android/adbkey` and `.android/adbkey.pub`. Those are available on desktop machine but not on an Android device. A quick solution could be to copy those over to the Android device and point `discover` call to them

**Comment by sharpordie** [comment]
@[dmitry-zaitsev](https://github.com/dmitry-zaitsev) I copied the adbkey files from my macOS machine to the Android application assets and pass them to the discover method as AdbKeyPair but unfortunately it returns null too.

```kotlin
// /data/user/0/com.example.composeapp/cache/adbkey
val created = File(context.cacheDir, "adbkey")
if (created.exists()) created.delete()
val inputStream = context.assets.open("adbkey")
val outputStream = FileOutputStream(created)
inputStream.copyTo(outputStream)

// /data/user/0/com.example.composeapp/cache/adbkey.pub
val created2 = File(context.cacheDir, "adbkey.pub")
if (created2.exists()) created2.delete()
val inputStream2 = context.assets.open("adbkey.pub")
val outputStream2 = FileOutputStream(created2)
inputStream2.copyTo(outputStream2)

val dadb = Dadb.discover("192.168.1.62", AdbKeyPair.read(created, created2))
val message = if (dadb == null) "Shield was not found :(" else "Shield was found :)"
Toast.makeText(context, message, Toast.LENGTH_LONG).show()
```

By the way, I don't understand why I need these two files with dadb. The official adb binary doesn't need them at all, I only have a dialog box on my android device that asks me if I want to allow the connection.

**Comment by dmitry-zaitsev** [comment]
The official adb binary implicitly refers to those files under the hood. By convention, it expects to find those keys under `.android` folder. `dadb` does the same when running from your host machine, but since you are running it from a device it can't locate those files.


To eliminate other possibilities, could you try to run `dadb` from a plain-Java/Kotlin project on your desktop machine? If it would succeed, the issue is likely somewhere within the setup of the Android app. If it will fail, I would highly suspect network to be the problem. Either way, happy to help debugging it.

**Comment by sharpordie** [comment]
Dadb is working on my desktop but only with proper key files, it means dadb does not work without a connection via the adb binary first. So dadb doesn't work by itself as an adb alternative. It would be great if dadb could create these files by itself if they don't exist.

Regarding Android, I still have to experiment, I wonder if you can even create a connection from a @Composable.

**Comment by sharpordie** [comment]
I confirm that dadb works perfectly on Android.

This code sample is working:

```kotlin
val privateKey = File(context.cacheDir, "adbkey")
if (privateKey.exists()) privateKey.delete()
val inputStream = context.assets.open("adbkey")
val outputStream = FileOutputStream(privateKey)
inputStream.copyTo(outputStream)

val publicKey = File(context.cacheDir, "adbkey.pub")
if (publicKey.exists()) publicKey.delete()
val inputStream2 = context.assets.open("adbkey.pub")
val outputStream2 = FileOutputStream(publicKey)
inputStream2.copyTo(outputStream2)

val queue = LinkedBlockingQueue<String>()

Executors.newSingleThreadExecutor().execute {
    val dadb = Dadb.discover("192.168.1.62", AdbKeyPair.read(privateKey, publicKey))
    val product = dadb?.shell("getprop ro.product.model")?.output?.trim()
    queue.add(product)
}

Toast.makeText(context, queue.take(), Toast.LENGTH_LONG).show()
```

But a method to create an AdkKeyPair like in adblib would be a nice addition.

**Comment by dmitry-zaitsev** [comment]
Awesome, glad it worked out!
