### ISSUE TITLE
Any hint about KeyPair?

### ISSUE THREAD

**Issue by shaikh-amaan-fm** [mobile-dev-inc/dadb#2]
Thank you so much for this library.
I request to put something about Authentication in documentation.

**Comment by Leland-Takamine** [comment]
I've updated `Dadb.create` and `Dadb.discover` to use the adb key at `~/.android/adbkey` by default and updated the README.

Commit: https://github.com/mobile-dev-inc/dadb/commit/814d654ff1e0d4e1809263155c183a85ceef026b

Feel free to reopen if you feel like the docs / api are still unclear!
