### ISSUE TITLE
Connect device via usb

### ISSUE THREAD

**Issue by JackuXL** [mobile-dev-inc/dadb#3]
How can I connect device via usb?

**Comment by Leland-Takamine** [comment]
Hi @JackuXL we don't yet support the USB transport. I'll keep this issue open as this is a known gap, but we don't have any immediate plans to address this. If we see that there are a lot of folks asking for this, we can prioritize this.

**Comment by icarapovic** [comment]
I came here with exactly the expectation that I can use this with many physical device I need to test with... So I guess out of luck atm?

**Comment by Leland-Takamine** [comment]
Yes @icarapovic this is not something we support yet. We are planning on building usb support but don't have any timeline on that yet.

**Comment by RohitVerma882** [comment]
When usb support come?

**Comment by RohitVerma882** [comment]
Need usb otg support 😥

**Comment by Leland-Takamine** [comment]
@JackuXL @icarapovic @RohitVerma882 

I've added some documentation on how to connect to a physical device using Dadb. I wanted to get all of your feedback on whether this solves your use case or if there is some reason you need / prefer built-in USB support in dadb?

https://github.com/mobile-dev-inc/dadb/blob/master/README.md#connecting-to-a-physical-device

**Comment by JackuXL** [comment]
> @JackuXL @icarapovic @RohitVerma882 
> 
> I've added some documentation on how to connect to a physical device using Dadb. I wanted to get all of your feedback on whether this solves your use case or if there is some reason you need / prefer built-in USB support in dadb?
> 
> https://github.com/mobile-dev-inc/dadb/blob/master/README.md#connecting-to-a-physical-device

@Leland-Takamine 
Thank you for your reply.
This method is very convenient for devices above Android 11, but for other ordinary users, it is troublesome to connect the USB device for a period of time, then disconnect and obtain the IP address of the device. 
Also, some special devices (especially in China) may have removed the WIFI ADB switch in AOSP, and it would be more convenient to use the USB connection directly.

**Comment by Leland-Takamine** [comment]
Thanks for the context @JackuXL!

Totally agree that USB support is more convenient for Android 10 and below or for devices that don't offer adb over wifi.

I've taken a look at USB libraries for Java and it looks like [usb4java](https://github.com/usb4java/usb4java) is our best bet. Problem is that it hasn't been updated in 4 years and lacks support for M1 macs.

Since there are [reasonable workarounds](https://github.com/mobile-dev-inc/dadb#connecting-to-a-physical-device) that exist today to connect to a physical device, we won't be prioritizing this in the near term. I'll update this thread if we're able to prioritize this. Contributions are of course absolutely welcomed here.

**Comment by championswimmer** [comment]
If I am not wrong, with v1.2.0 `AdbServerDadb.create()` makes this possible right?

**Comment by Leland-Takamine** [comment]
> If I am not wrong, with v1.2.0 `AdbServerDadb.create()` makes this possible right?

@championswimmer This is indeed possible via the experimental `AdbServerDadb.create()` API. Once thing to note though is that this method requires an adb binary to be available on the machine.

**Comment by Leland-Takamine** [comment]
Closing this out as you are now able to connect to a USB device using the AdbServerDadb.create() API (soon to be renamed to AdbServer.createDadb)

**Comment by Ran-Xing** [comment]
@Leland-Takamine Regarding the adb server, you can try using [Android's USB Host API](https://github.com/mingzhixian/Easycontrol/blob/master/easycontrol/app/src/main/java/top/saymzx/easycontrol/app/adb/Adb.java) to implement the ADB protocol. 

I'm currently working on a Scrcpy Android app and using your repository. I hope you can port this logic to dadb as soon as possible.

If you're interested, you can [download my app](https://github.com/XRSec/scrcpy-mobile) and try it out; it's partially compatible with English.

If you plan to use GPT to improve the ADB Server related protocols in the near future, please let me know. I'm not in a rush for that part of the code; I still need to improve the audio and video decoding protocols. The USB protocol can be processed later.
