### ISSUE TITLE
dadb.AdbStreamClosed: ADB stream is closed for localId: e2527064

### ISSUE THREAD

**Issue by nassendelft** [mobile-dev-inc/dadb#4]
I'm getting the following error when calling `dadb.install`.

```
dadb.AdbStreamClosed: ADB stream is closed for localId: e2527064
```
It looks like it returns a close command immediately when it receives the abb_execute command.

When the server receives the message it only returns the close command if it can't read the response for some reason.
https://cs.android.com/android/platform/superproject/+/master:packages/modules/adb/adb.cpp;drc=867c71e5114e76b4f64e9f38e1be060fd9ba3a26;l=475

Sending shell commands work fine. Calling the install command through adb on my local machine to the same target host also works fine.

**Comment by Leland-Takamine** [comment]
Thanks for reporting this. Would you mind providing some more details on your setup? I'm hoping to be able to repro in order to debug this.

**Comment by nassendelft** [comment]
Sure, what do you need to know?
I've tested this with 2 remote devices i have on my network and a local running emulator all with the same error.
I'm running this on osx 11.6 with jvm16

**Comment by Leland-Takamine** [comment]
What version of Android emulator are you running?

**Comment by nassendelft** [comment]
9, same as the actual device i was trying

**Comment by nassendelft** [comment]
I just tested a few emulators and it seems to not work on <= 9 devices.
After going through google's sources my guess would be that streaming install is not supported but pushes the file to android tmp file system and then call the pm install shell command instead:
https://cs.android.com/android/platform/superproject/+/master:packages/modules/adb/client/adb_install.cpp;l=518;drc=867c71e5114e76b4f64e9f38e1be060fd9ba3a26;bpv=0;bpt=1

using push + install works fine

**Comment by Leland-Takamine** [comment]
@nassendelft I truly appreciate you putting in the time to debug this on your end. I will push up a fix ASAP and deploy. I'll update this thread once the new version is available.
