### ISSUE TITLE
Feature Request: programmatic logging control

### ISSUE THREAD

**Issue by yschimke** [mobile-dev-inc/dadb#6]
Logging is fixed at process start. And always to println()

```
private val ENABLED = "true" == System.getenv("DADB_LOGGING")
```

I wanted to use a connection for a sustained period but control logging.   Is there a plan to adopt a logging framework (slf4j?) that would allow changing logging.

**Comment by Leland-Takamine** [comment]
Definitely open to this improvement. If you happen to have the bandwidth, we'd definitely welcome a pull request for this.

**Comment by Leland-Takamine** [comment]
Not prioritizing this in the near term so closing this out for now
