### ISSUE TITLE
[Discussion] KMP support

### ISSUE THREAD

**Issue by yschimke** [mobile-dev-inc/dadb#9]
I'm trying to use a combination of dadb and grpc to the emulator to implement some useful functions when using emulators.

This led me to a couple of questions

1) Have you considered Kotlin multiplatform support? You are already using Okio, which is KMP enabled and there is code for KMP Certificate handling code in github.com/cashapp/certifikit.  Generally seems like a incremental change that could unlock a lot of other cases.
2) Have you considered supporting gRPC in Dadb also?

I have a working implementation of gRPC using Square's Wire project (again KMP native)

https://github.com/yschimke/emulator-tools/blob/main/src/jvmMain/kotlin/ee/schimke/emulatortools/Main.kt#L41-L48

again, please close if this it undesired or out of scope and I'll maintain the bits I need separately.

**Comment by Leland-Takamine** [comment]
For now, (2) is out of scope for the dadb project. However, I do think KMP is a worthwhile investigation. I don't have much experience with KMP so open to contributions.

Note: Since (2) is out of scope, I updated the title of the issue to focus on (1).

**Comment by Leland-Takamine** [comment]
It doesn't look like we'll be able to prioritize this in the short term, so I'm closing this out for now
